### ISSUE TITLE
Move link and flag icons to start of line

### ISSUE THREAD

**Issue by originalfoo** [lgommans/factorio-serverlist#9]
Will make display look more consistent if the flag and link icons appeared before the server name

**Comment by lgommans** [comment]
Good idea. I've toyed around with it a bit and this looks the best to me (link in front; flag with other info). What do you think?

![](https://snag.gy/9eb5Tf.jpg)

If you want to try other layouts, modify [www/res/serverlist.js line 278](https://github.com/lgommans/factorio-serverlist/blob/master/www/res/serverlist.js#L278-L283).

**Comment by originalfoo** [comment]
That looks much better! Might look cleaner without the pipe icons (as there's orange icons delimiting the fields)?

**Comment by lgommans** [comment]
Pipes or no pipes doesn't make much of a difference to me, so if you think it looks better without, why not? ^^
